kieserver:
  location: http://localhost:8090/rest/server
  serverId: business-application-service
  serverName: business-application-service
spring:
  datasource:
    driver-class-name: org.postgresql.xa.PGXADataSource
    password: jbpm
    url: jdbc:postgresql://localhost:5432/jbpm
    username: jbpm
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        show_sql: false
  jta:
    narayana:
      transaction-manager-id: 1
